name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [windows-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install Pillow==7.2.0
      - name: Run tests
        run: coverage run tests.py
      - name: Tests report
        run: coverage report
      - name: Generate .exe file
        run: pyinstaller ezFilter.py
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: EzFile.exe